= Onlines fonds vedtekter
:toc:

== §1 Fondets Navn
Fondets navn er “Onlines fond”, heretter kalt fondet.

== §2 Formål
Fondets formål er å gi Online, linjeforeningen for informatikk, en økonomisk trygghet
og sørge for at Online sitt økonomiske overskudd fordeles rettferdig på nåværende og
fremtidige medlemmer av Online.

== §3 Generalforsamlingen

Generalforsamlingen er fondets øverste organ og er uavhengig av gjeldende fondstyre. Generalforsamlingen avholdes samtidig med Onlines ordinære generalforsamling.
For fondets generalforsamling gjelder følgende av Onlines vedtekter: 5.1, 5.4 og 5.5.
Den ordinære generalforsamlingen skal behandle egne punkter med årsberetning,
innsendte saker, vedtektsendringer, valg, regnskap og budsjettforslag for neste budsjettperiode. Alle medlemmer i Online har rett til å levere saks- og vedtektsforslag.

=== 3.1 Ekstraordinær generalforsamling

Denne kan innkalles av Fondstyret, eller om minst det laveste av ti (10) eller 1/8
av medlemmene i Online ønsker det. Fristene for å kalle inn til ekstraordinær generalforsamling er halvert i forhold til fristene for ordinær, jamfør Onlines vedtekter
5.1.
Ekstraordinær generalforsamling skal kun den(de) saken(e) som står på dagsorden
for den ekstraordinære generalforsamlingen.

=== 3.2 Organisering

Ved generalforsamling er disse vervene nødvendig:

* Ordstyrer
* To referenter - skriver referat og samarbeider om renskriving
* Minst to til tellekorps - teller opp stemmene ved avstemming

Ved generalforsamling som avholdes samtidig med generalforsamling i regi av Online,
vil tilsvarende verv ved denne automatisk tilfalle disse vervene.

=== 3.3 Gjennomføring av valget

Dersom det er mer enn en kandidat til et verv skal det avholdes anonymt valg for
det aktuelle vervet. Man kan stemme “ingen” på valget. For å regnes som vinner av
valget må en kandidat få minstover halvparten (1/2) av stemmene. Ved manglende
flertall fjernes kandidaten med færrest stemmer og valget går inn i en ny runde.
Ved manglende flertall på kandidat med flest stemmer og stemmelikhet på de med
færrest stemmer vil det avholdes en fullstendig ny runde.
Innehavere av verv sitter inntil endt generalforsamling hvor det er gjennomført et
godkjent valg for det respektive vervet. Dersom generalforsamlingen ikke klarer å
gjennomføre et valg må det kalles inn til ekstraordinær forsamling innen tre dager
etter endt ordinær generalforsamling.
Ved opptelling av hemmelig valg skal tellekorps sitte i salen.

==== 3.3.1 Fraskrivelse av rett til å stille til valg

Personer som er innstilt med et av følgende verv under Generalforsamlingen fraskriver
seg sin rett til å stille til alle andre valg.

* Ordstyrer
* Tellekorps

Med å stille til andre valg menes det at man ikke kan stille, eller bli nominert, til
andre verv under Generalforsamlingen og valg til Fondstyret.

== §4 Fondstyret

Fondstyret styrer Onlines fond mellom generalforsamlingene. Fondstyrets medlemmer
velges på generalforsamlingen og skal drive fondet mellom generalforsamlingene. For
at Fondstyret skal være beslutningsdyktig må minst halvparten av representantene
være tilstede.
Ingen kan inneha to verv i Fondstyret. Fondstyrets møter er lukket, men gjester kan
inviteres dersom Fondstyret ønsker dette. Fondstyret skrives med stor ’F’ på samme
måte som egennavn.

=== 4.1 Fondstyrets sammensetning

Fondstyret består av:

* Økonomiansvarlig i Online
* Ridderne av det indre lager-medlem 1
* Ridderne av det indre lager-medlem 2
* Tidligere medlem fra Onlines Hovedstyre 1
* Tidligere medlem fra Onlines Hovedstyre 2
* Onlinemedlem 1
* Onlinemedlem 2
Alle medlemmer av Fondstyret har stemmerett. Fondstyret velger sin egen leder. Ved
stemmelikhet teller Fondstyret sin leder dobbelt.

=== 4.2 Valg av Fondstyre

Fondstyret skal velges på generalforsamlingen, på samme måte som medlemmer til
Onlines Hovedstyre som beskrevet i Onlines vedtekter av 5.6, med unntak av følgende:
I oddetallsår skal følgende styremedlemmer velges på nytt: Ridderne av det indre
lager-medlem 1, tidligere medlem fra Onlines Hovedstyre 1, og Onlinemedlem 1.
I partallsår skal følgende styremedlemmer velges på nytt: Ridderne av det indre
lager-medlem 2, tidligere medlem fra Onlines Hovedstyre 2, og Onlinemedlem 2.

=== 4.3 Krav til kandidater ved valg

En kandidat til valg kan ikke være valgt til medlem av Onlines Hovedstyre. Avtroppende Hovedstyre kan stille til valg.
Kandidater for stillingene som tidligere medlem fra Onlines Hovedstyre kan ikke være
medlem av Ridderne av det Indre Lager, eller tidligere medlem i Fondstyret.
Kandidater til stillingene som Onlinemedlem kan ikke være medlem av Ridderne av
det Indre Lager, tidligere medlem av Onlines Hovedstyre, eller tidligere medlem i
Fondstyret.
Minst et Onlinemedlem i Fondstyret skal ikke være nåværende eller tidligere medlem
av en kjernekomité i Online.

=== 4.4 Trekke seg fra verv

Dersom et medlem av Fondstyret trekker seg før perioden deres er over skal Fondstyret fylle den aktuelle stillingen med et medlem som oppfyller kravene i 4.3. Stillingen
skal velges på nytt ved neste ordinære generalforsamling.

=== 4.5 Mislighold av verv

Om et fondstyremedlem misligholder sine arbeidsoppgaver, kan ethvert medlem av
Online stille mistillitsforslag overfor vedkommende. Mistillitsforslaget skal leveres
skriftlig til Fondstyret, som skal behandle saken. Ved mistillitsforslag mot et fondstyremedlem blir den anklagede suspendert inntil Fondstyret har kommet med en
avgjørelse. Mistillitsforslaget leses opp i Fondstyret, deretter skal den anklagede få
en mulighet til å forsvare seg før Fondstyret diskuterer og avgjør saken uten den
anklagede til stede. Dersom det stille mistillitsforslag til flere styremedlemmer av
gangen skal medlemmene kalle inn til ekstraordinær generalforsamling etter 3.1.

== §5 Medlemskap

Ethvert medlem av Online, linjeforeningen for informatikk, er også et medlem av
Onlines fond.
Alle medlemmer av Onlines fond har møte-, tale- og stemmerett på fondets generalforsamling.

== §6 Økonomi

=== 6.1 Styring av fondet
Fondets økonomi styres i samsvar med Fondstyrets styredokument.

=== 6.2 Endring av styredokumentet
Fondstyret kan når som helst endre styredokumentet, men enhver endring krever godkjenning fra både Hovedstyret og Bank- og Økonomikomiteen.

== §7 Søknader om midler

=== 7.1 Krav til søknader

Alle Onlines medlemmer kan søke Onlines fond om penger. Søknader må være på
minst 10 000 kr. Onlines Hovedstyre kan videresende mottatte søknader til fondet,
uavhengig av beløpets størrelse.

=== 7.2 Godkjenning av søknader

Søknader på mindre enn 100 000 kr, kan behandles av Fondstyret. En slik søknad
godkjennes av Fondstyret med alminnelig flertall. Søknader på større beløp enn dette
skal behandles på fondets generalforsamling, eventuelt på ekstraordinær generalforsamling dersom søknadens omstendigheter krever svar før neste generalforsamling.

=== 7.3 Årlig beløpsbegrensninger

Det er ingen begrensninger på hvor mange søknader Fondstyret kan godkjenne. Totalsummen på godkjente søknader kan verken overstige 300 000 kr eller 50% av fondets
størrelse i løpet av et kalenderår. Dersom det ønskes å bruke mer enn dette må
det legges frem som et saksforslag på Onlines fond’s generalforsamling, eventuelt på
ekstraordinær generalforsamling dersom omstendighetene krever det.

=== 7.4 Søknadens innhold

Søknaden skal inneholde hvem som søker, formålet med søknaden og antall kroner
det søkes om. Søknaden skal være velbegrunnet og ha som hensikt å komme flest
mulig medlemmer av Online til gode.

== §8 Oppløsning av fondet

=== 8.1 Vedtak

Vedtak om fondets oppløsning tre↵es av ordinær generalforsamling med 3/4 flertall,
og deretter 3/4 flertall ved ekstraordinær generalforsamling tre til seks måneder etter
ordinær generalforsamling.

=== 8.2 Midler

Ved oppløsning skal midler som fondet disponerer stå uberørt i tre år, dette for å
oppfordre til gjenopptak av fondet. Dersom det går tre år etter oppløsningen uten
at fondet blir gjenopptatt, tilfaller fondets midler Online, linjeforeningen for informatikk. Om Online oppløses i dette tidsrommet skal midler som fondet disponerer
overføres i henhold til Onlines vedtekter §7.2. Onlines generalforsamling kan ved
kvalifisert flertall umiddelbart overføre midler til andre organisasjoner som jobber
for studenter.